---
general:
  cpiApiServiceKeyCredentialsId: "iscicdtest"
  integrationFlowId: "testiflow"
stages:
  Upload:
    enabled: true
  Deploy:
    enabled: true
  Integration Test:
    enabled: true
steps:
  integrationArtifactUpload:
    packageId: "testpackage"
    integrationFlowName: "testiflow"
httpCall:
    url: ${integrationArtifactGetServiceEndpoint.response.url}  # This will be HTTPS
    method: POST
    contentType: text/plain
    payload: ./testpayload.txt

