---
general:
  cpiApiServiceKeyCredentialsId: "iscicdtest"
  integrationFlowId: "testiflow"
stages:
  Upload:
    enabled: true
  Deploy:
    enabled: true
  Integration Test:
    enabled: true
steps:
  integrationArtifactUpload:
    packageId: "testpackage"
    integrationFlowName: "testiflow"

